### ISSUE TITLE
Fix breadcrumbs on for individual bio pages

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/tcf#33]
Breadcrumb link for "People" goes to this magnificent page:
https://trianglecf.beta.unitymakes.us/people/

**Comment by andrewmarino** [comment]
Yikes!

So for some reason, the simple team post type has `has_archive` set to false but the breadcrumbs plugin still outputs this info and it leads to a broken / weird page. I had to do a pretty janky override to get around this.
